"""Running code with nsml
==========================

This example introduces the nsml interactive mode, which directly prints the
output generated by the user provided code to his console.
"""

import os

# Run nsml with -i (interactive option)
# $ nsml run  01-hello_nsml.py -i
print('hello NSML!')
